export const APP_STRINGS = {
  applicationTitle: 'Task Timeline Manager',
  applicationSubtitle:
    'Plan work, manage dependencies, and move through snapshot history with confidence.',
  toolbarBadge: 'Productivity Workspace',
  toolbarResetSelection: 'Clear selection',
  toolbarTaskCount: 'Tasks',
  toolbarSnapshotCount: 'Snapshots',
  toolbarCurrentStep: 'Current step',
  formTitle: 'Task details',
  formDescription:
    'Create a task or update the selected task. Parent schedule shifts cascade through descendants.',
  formCreateTitle: 'Create task',
  formUpdateTitle: 'Update task',
  formTitleLabel: 'Title',
  formStartLabel: 'Start date and time',
  formEndLabel: 'End date and time',
  formParentLabel: 'Parent task',
  formParentPlaceholder: 'No parent',
  formSubmitCreate: 'Add task',
  formSubmitUpdate: 'Save changes',
  formCancelEdit: 'Cancel edit',
  formInvalidRange: 'End date and time must be after the start date and time.',
  taskListTitle: 'Task list',
  taskListDescription:
    'Root tasks appear first. Children stay nested under their parent. Orphaned tasks remain visible at the root level.',
  emptyStateLabel: 'No tasks available. Use the form to add the first task.',
  orphanedStatusLabel: 'Orphaned',
  activeStatusLabel: 'Active',
  rootTaskLabel: 'Root task',
  childTaskLabel: 'Child task',
  childChainLabel: 'Child chain',
  rootCountSuffix: 'roots',
  editActionLabel: 'Edit task',
  removeActionLabel: 'Remove task',
  noTaskSelectedLabel: 'No task selected',
  editingTaskPrefix: 'Editing',
  historyTitle: 'Snapshot history',
  historyDescription:
    'Drag the slider to preview a snapshot step and release the thumb to commit time travel.',
  historyStepLabel: 'Step',
  historySnapshotLabel: 'Snapshot',
  historyEmptyLabel: 'No snapshots yet',
  historyDockTitle: 'History dock',
  demoParentTaskTitle: 'Launch preparation',
  demoChildTaskTitle: 'Draft stakeholder brief',
  demoGrandchildTaskTitle: 'Review dependency notes',
  demoSecondRootTaskTitle: 'Release planning',
} as const;
